services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ry-vue
    ports:
      - "3306:3306"
    volumes:
      - /home/dockerfile/java/manniu_base/mysqlData:/var/lib/mysql
    networks:
      - ruoyi-net

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - /home/dockerfile/java/manniu_base/redisData:/data
    networks:
      - ruoyi-net

  ruoyi-admin:
    build:
      context: ./ruoyi-admin
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
    networks:
      - ruoyi-net

networks:
  ruoyi-net:
